ecommerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ecommerce' # This will be like this: {% url 'ecommerce:detail' item.id %} on our templates. 
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^products/$', views.products, name='products'),
	url(r'^product/(?P<product_id>[0-9]+)/$', views.single_product, name='single_product'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	
	url(r'^user/', include([
        url(r'^login/$', views.user_login, name='user_login'),
		url(r'^register/$', views.user_register, name='user_register'),
		url(r'^account/$', views.user_account, name='user_account'),
		url(r'^products/$', views.user_products, name='user_products'),
		url(r'^product/create/$', views.user_product_create, name='user_product_create'),
		url(r'^product/update/(?P<product_id>[0-9]+)/$', views.user_product_update, name='user_product_update'),
		url(r'^product/update/set-featured-image/$', views.set_featured_image),
		url(r'^product/update/unset-image/$', views.unset_image),
		url(r'^product/unset-product/$', views.unset_product),
		url(r'^logout/$', views.logout),
    ])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^ecommerce/', include('ecommerce.urls')), # Include ecommerce app views. 
    url(r'^admin/', admin.site.urls),
]

ecommerce/models.py
from django.db import models
from django.contrib.auth.models import User

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=30)
    about = models.TextField()
    
class Product(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField()
    excerpt = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    status = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField()
    author = models.PositiveIntegerField()
    featured_image = models.CharField(max_length=300)

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField()

ecommerce/forms.py
from django import forms

class RegisterForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	
class AccountForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Leave blank if no change'}), required=False)
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), required=False)
	about_me = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}), required=False)
	
class CreateProductForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}))
	excerpt = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows': '7'}), required=False)
	price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Amount'}))
	status = forms.CharField(widget=forms.Select(choices=(('1', 'Active'),('0', 'Inactive'),), attrs={'class':'form-control'}))
	quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
	
class UpdateProductForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'id': 'ck-editor-area'}))
	excerpt = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'rows': '7'}), required=False)
	images = forms.CharField(widget=forms.FileInput(attrs={'class':'form-control image-input', 'accept': 'image/*', 'multiple': 'multiple'}), required=False)
	price = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Amount'}))
	status = forms.CharField(widget=forms.Select(choices=(('1', 'Active'),('0', 'Inactive'),), attrs={'class':'form-control'}))
	quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))

ecommerce/views.py
import os

from django.contrib.auth import authenticate, login, logout as django_logout # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .models import Member, Product, Image
from .forms import *
from .helpers import Helpers

def index(request):
	return render(request, Helpers.get_url('index.html'))

def single_product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	product_images = product.image_set.all()
	images = []
	
	if product_images:
		for data in product_images:
			images.append({"small": Helpers.get_path(str(data.image)), 'big': Helpers.get_path(str(data.image))})
	
	return render(request, Helpers.get_url('product/single.html'), {'product': product, 'images': str(images).replace("'", '"')})
	
def products(request):
	if request.method == 'POST':
		pagination_content = ""
		page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
		page = int(page_number)
		name = request.POST['data[name]']
		sort = '-' if request.POST['data[sort]'] == 'DESC' else ''
		search = request.POST['data[search]']
		max = int(request.POST['data[max]'])
		
		cur_page = page
		page -= 1
		per_page = max # Set the number of results to display
		start = page * per_page
		
		# If search keyword is not empty, we include a query for searching 
		# the "content" or "name" fields in the database for any matched strings.
		if search:		 
			all_posts = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search)).exclude(status = 0).order_by(sort + name)[start:per_page]
			count = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search)).exclude(status = 0).count()
			
		else:
			all_posts = Product.objects.exclude(status = 0).order_by(sort + name)[start:cur_page * max]
			count = Product.objects.exclude(status = 0).count()
		
		if all_posts:
			for post in all_posts:
				pagination_content += '''
					<div class='col-sm-3'>
						<div class='panel panel-default'>
							<div class='panel-heading'>%s</div>
							<div class='panel-body p-0 p-b'>
								<a href='%s'>
									<img src='%s' width='%s' class='img-responsive'>
								</a>
								<div class='list-group m-0'>
									<div class='list-group-item b-0 b-t'>
										<i class='fa fa-calendar-o fa-2x pull-left ml-r'></i>
										<p class='list-group-item-text'>Price</p>
										<h4 class='list-group-item-heading'>$%s</h4>
									</div>
									<div class='list-group-item b-0 b-t'>
										<i class='fa fa-calendar fa-2x pull-left ml-r'></i>
										<p class='list-group-item-text'>On Stock</p>
										<h4 class='list-group-item-heading'>%d</h4>
									</div>
								</div>
							</div> 
							<div class='panel-footer'>
								<a href='%s' class='btn btn-primary btn-block'>View Item</a>
							</div>
						</div>
					</div>
				''' %(post.name, Helpers.get_path('product/' + str(post.id)), Helpers.get_path(post.featured_image), '100%', post.price, post.quantity, Helpers.get_path('product/' + str(post.id)))
		else:
			pagination_content += "<p class='bg-danger p-d'>No results</p>"
		
		return JsonResponse({
			'content': pagination_content, 
			'navigation': Helpers.nagivation_list(count, per_page, cur_page)
		})
	else:	
		return render(request, Helpers.get_url('product/index.html'))
	
def about(request):
	return render(request, Helpers.get_url('about.html'))
	
def contact(request):
	return render(request, Helpers.get_url('contact.html'))

def user_login(request):
	# Redirect if already logged-in
	if request.user.is_authenticated():
		return HttpResponseRedirect(Helpers.get_path('user/account'))
	
	if request.method == 'POST':
		# Process the request if posted data are available
		username = request.POST['username']
		password = request.POST['password']
		# Check username and password combination if correct
		user = authenticate(username=username, password=password)
		if user is not None:
			# Success, now let's login the user. 
			login(request, user)
			# Then redirect to the accounts page.
			return HttpResponseRedirect(Helpers.get_path('user/account'))
		else:
			# Incorrect credentials, let's throw an error to the screen.
			return render(request, Helpers.get_url('user/login.html'), {'error_message': 'Incorrect username and / or password.'})
	else:
		# No post data availabe, let's just show the page to the user.
		return render(request, Helpers.get_url('user/login.html'))
 
def user_account(request):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Create instance of the form and populate it with requests
	form = AccountForm(request.POST)
	
	# Redirect if not logged-in
	if request.user.is_authenticated() == False:
		return HttpResponseRedirect(Helpers.get_path('user/login')) 
	
	if request.method == 'POST':
		if form.is_valid():	
			# Query data of currently logged-in user.
			user = User.objects.get(username=request.user.username)
			
			# Check if username exists
			if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != form.cleaned_data['username']:
				err_succ['message'] = 'Username aleady taken, please enter a different one.'
			
			# Check if email exists		
			elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data['email']:
				err_succ['message'] = 'Email already taken, please enter a different one'
				
			elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data['password']:
				# Check if passwords match
				if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
					err_succ['message'] = 'New password do not match.'
				
				# Check if old password is correct
				elif not user.check_password(form.cleaned_data['old_password']):
					err_succ['message'] = 'Incorrect old password.'
					
			else:
				user.username = form.cleaned_data['username']
				user.first_name = form.cleaned_data['first_name']
				user.last_name = form.cleaned_data['last_name']
				
				user.member.phone_number = form.cleaned_data['phone_number']
				user.member.about = form.cleaned_data['about_me']
				
				# Save new password if passes above validations
				if form.cleaned_data['password']:
					user.set_password(form.cleaned_data['password'])
				
				# Save posted fields to their respective tables
				user.member.save()
				user.save()
				
				# Show success message
				err_succ['status'] = 1
				err_succ['message'] = 'Account successfully updated.'
			
		return JsonResponse(err_succ)
	else:
		# Let's define intial data that we are going to use to populate our account form.
		user_data = {
			'username': request.user.username, 
			'email': request.user.email, 
			'first_name': request.user.first_name, 
			'last_name': request.user.last_name, 
			'phone_number': request.user.member.phone_number, 
			'about_me': request.user.member.about 
		}
		# Render the account form
		return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})

def user_products(request):
	# Redirect if not logged-in
	if request.user.is_authenticated() == False:
		return HttpResponseRedirect(Helpers.get_path('user/login'))
	
	if request.method == 'POST':
		pagination_content = ""
		page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
		page = int(page_number)
		name = request.POST['data[th_name]']
		sort = '-' if request.POST['data[th_sort]'] == 'DESC' else ''
		search = request.POST['data[search]']
		max = int(request.POST['data[max]'])
		
		cur_page = page
		page -= 1
		per_page = max # Set the number of results to display
		start = page * per_page
		
		# If search keyword is not empty, we include a query for searching 
		# the "content" or "name" fields in the database for any matched strings.
		if search:		 
			all_posts = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search), author = request.user.id).order_by(sort + name)[start:per_page]
			count = Product.objects.filter(Q(content__contains = search) | Q(name__contains = search), author = request.user.id).count()
			
		else:
			all_posts = Product.objects.filter(author = request.user.id).order_by(sort + name)[start:cur_page * max]
			count = Product.objects.filter(author = request.user.id).count()
		
		if all_posts:
			for post in all_posts:
				pagination_content += '''
					<tr>
						<td><a href="%s"><img src='%s' width='100' /></a></td>
						<td>%s</td>
						<td>$%s</td>
						<td>%s</td>
						<td>%s</td>
						<td>%s</td>
						<td>
							<a href='%s' class='text-success'>  
								<span class='glyphicon glyphicon-pencil' title='Edit'></span>
							</a> &nbsp; &nbsp;
							<a href='#' class='text-danger delete-product' item_id='%s'>
								<span class='glyphicon glyphicon-remove' title='Delete'></span>
							</a>
						</td>
					</tr>
				''' %(Helpers.get_path('user/product/update/' + str(post.id)), Helpers.get_path(post.featured_image), post.name, post.price, post.status, post.date, post.quantity, Helpers.get_path('user/product/update/' + str(post.id)),  post.id)
		else:
			pagination_content += "<tr><td colspan='7' class='bg-danger p-d'>No results</td></tr>"
		
		return JsonResponse({
			'content': pagination_content, 
			'navigation': Helpers.nagivation_list(count, per_page, cur_page)
		})
	else:	
		return render(request, Helpers.get_url('product/user.html'))
	
def user_product_create(request):
	err_succ = {'status': 0, 'message': 'An unknown error occured'}
	
	# Redirect if not logged-in
	if request.user.is_authenticated() == False:
		return HttpResponseRedirect(Helpers.get_path('user/login'))
	

ecommerce/templates/ecommerce/product/create.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container">
		<p class="ml-b"><a href = "/ecommerce/user/products" class="ml-b text-success"><span class="glyphicon glyphicon-chevron-left"></span> All products</a></p>
		
		<div class="panel panel-default">
			<div class="panel-heading">
				Create Product
			</div>
			<div class="panel-body">
				<form method="post" action="{% url 'ecommerce:user_product_create' %}" class="create-product">
					{% csrf_token %}
					<div class="col-md-8">
						<div class="form-group">
							<label for="{{ form.name.id_for_label }}">Name*</label>
							{{ form.name }}
						</div>
						<div class="form-group">
							<label for="{{ form.content.id_for_label }}">Description</label>
							{{ form.content }}
						</div>
						<div class="form-group">
							<label for="{{ form.excerpt.id_for_label }}">Short Description</label>
							{{ form.excerpt }}
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label for="{{ form.price.id_for_label }}">Price*</label>
							<div class="input-group">
								<div class="input-group-addon">$</div>
								{{ form.price }}
							</div>
						</div>
						<div class="form-group">
							<label for="{{ form.status.id_for_label }}">Status</label>
							{{ form.status }}
						</div>
						<div class="form-group">
							<label for="{{ form.quantity.id_for_label }}">Quantity*</label>
							{{ form.quantity }}
						</div>
						<input type="submit" class="btn btn-success" value="Submit" />
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/index.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container products-view-all">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />
		</form>
		
		<div class="clearfix">
			<article class="navbar-form navbar-left p-0 m-0 ml-b">
				<div class="form-group">
					<label>Per Page: </label>
					<select class="form-control post_max m-b">
						<option value="4">4</option>
						<option value="8" selected>8</option>
						<option value="16">16</option>
					</select>
					<label>Search Keyword: </label>
					<input type="text" class="form-control post_search_text m-b" placeholder="Enter a keyword" />
				</div>
				<div class="form-group">
					<label>Order By: </label>
					<select class="form-control post_name m-b">
						<option value="name">Title</option>
						<option value="price">Price</option>
						<option value="quantity">Quantity</option>
					</select>
					<select class="form-control post_sort m-b">
						<option value="ASC">ASC</option>
						<option value="DESC">DESC</option>
					</select>
				</div>
				<input type = "submit" value = "Filter" class = "btn btn-primary post_search_submit m-b" />
			</article>
		</div>
		
		<hr />
		
		<div class="clearfix">
			<div class="pagination-container clearfix"></div>
			<div class="pagination-nav"></div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/single.html
{% extends "ecommerce/base.html" %}

{% block content %}		
	<div class="container products-view">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					{{ product.name }}
				</div>
				<div class="panel-body">
					<input type = "hidden" class = "item-images-json" value = '{{ images }}' />
					<div class = "imageviewer">
						<div class = "image-container"></div>
						<span class = "glyphicon glyphicon-chevron-left prev"></span>
						<span class = "glyphicon glyphicon-chevron-right next"></span>
						
						<div class = "footer-info">
							<span class = "current"></span>/<span class="total"></span>
						</div>
					</div>
				
					<hr />
					<h3>Product Description</h3>
					{{ product.content|safe }}
				</div>
			</div>
		</div>
		
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					Product Details
				</div>
				<div class="panel-body">
					<h2 class="text-danger m-0 ml-b">${{ product.price }} <small>only</small></h2>
					
					<div class="clearfix">
						<div class="col-md-6">
							<span class="sr-only">Four out of Five Stars</span>
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
							<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
							<span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
							<span class="label label-success">7</span>
						</div>
						<div class="col-md-6">
							<a href="#_" class="monospaced"><span class="glyphicon glyphicon-pencil"></span> Write a Review</a>
						</div>
					</div>
					
					<hr />
					
					<p><strong>Date Posted</strong>: {{ product.date }}</p>
					<p><strong>On Stock</strong>: {{ product.quantity }}</p>
					
					<hr />
					
					<a href="#_" class="btn btn-success btn-block"><span class="glyphicon glyphicon-shopping-cart"></span> Add to Cart</a>
					<a href="#_" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-star"></span> Add to Wishlist</a>
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					Reviews
				</div>
				<div class="panel-body">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/update.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container item-edit" id="item-{{ product.id }}">
		<p class="ml-b"><a href = "/ecommerce/user/products" class="ml-b text-success"><span class="glyphicon glyphicon-chevron-left"></span> All products</a></p>
		
		<div class="panel panel-default">
			<div class="panel-heading">
				Edit Product
			</div>
			<div class="panel-body wave-box-wrapper">
				<div class="wave-box"></div>
				<form action="{% url 'ecommerce:user_product_update' product.id %}" method="post" enctype="multipart/form-data" class="update-product" >
					{% csrf_token %}
					<div class="col-md-8">
						<div class="form-group">
							<label for="{{ form.name.id_for_label }}">Name</label>
							{{ form.name }}
						</div>
						<div class="form-group">
							<label for="{{ form.content.id_for_label }}">Description</label>
							{{ form.content }}
						</div>
						<div class="form-group">
							<label for="{{ form.excerpt.id_for_label }}">Short Description</label>
							{{ form.excerpt }}
						</div>
						<div class="form-group ml-t">
							<label for="{{ form.images.id_for_label }}">Upload Images</label>
							{{ form.images }}
							<hr />
							
							<div class = "clearfix m-t images-section">
								{% if product.image_set.all %}
									{% for data in product.image_set.all %}
										<div class = "col-sm-3">
											<span class="unset-image glyphicon glyphicon-remove text-danger lead m-0 c-p" id="unset-{{ data.id }}" title="Delete image"></span>
											{% if product.featured_image == data.image %}
												<span class="set-featured-image glyphicon glyphicon-star lead m-0 c-p" title="Set as featured image" id="featured-{{ data.image }}" style="color: #E4C317"></span>
											{% else %}
												<span class="set-featured-image glyphicon glyphicon-star-empty lead m-0 c-p" title="Set as featured image" id="featured-{{ data.image }}"></span>
											{% endif %}
											<img src = "/ecommerce/{{ data.image }}" class = "img-thumbnail img-responsive" />
										</div>
										
										{% if forloop.counter|divisibleby:4 == 1 %}
											<div class = "clearfix"></div>
										{% endif %}
									{% endfor %}
								{% else %}
									<p class = "alert alert-danger no-item-images">No images found</p>
								{% endif %}
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label for="{{ form.price.id_for_label }}">Price</label>
							<div class="input-group">
								<div class="input-group-addon">$</div>
								{{ form.price }}
							</div>
						</div>
						<div class="form-group">
							<label for="{{ form.status.id_for_label }}">Status</label>
							{{ form.status }}
						</div>
						<div class="form-group">
							<label for="{{ form.quantity.id_for_label }}">Quantity</label>
							{{ form.quantity }}
						</div>
						<input type="submit" class="btn btn-success" value="Update" />
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/user.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container products-view-user">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />
		</form>
		
		<article class="navbar-form navbar-left p-0 m-0 ml-b">
			<div class="form-group">
				<label>Per Page: </label>
				<select class="form-control post_max">
					<option value="5">5</option>
					<option value="10" selected>10</option>
					<option value="15">15</option>
				</select>
				<label>Search Keyword: </label>
				<input type="text" class="form-control post_search_text" placeholder="Enter a keyword">
			</div>
			<input type = "submit" value = "Filter" class = "btn btn-primary post_search_submit" />
		</article>
		
		<a href="/ecommerce/user/product/create/" class="btn btn-success pull-right">Add New</a>
		
		<br class = "clear" />
		
		<div class = "wave-box-wrapper">
			<div class = "wave-box"></div>
			<table class = "table table-striped table-post-list no-margin">
				<thead>
					<tr>
						<th>Image</th>
						<th id = "name" class = "active"><a href = "#">Name</a></th>
						<th id = "price"><a href = "#">Price</a></th>
						<th id = "status"><a href = "#">Status</a></th>
						<th id = "date"><a href = "#">Date</a></th>
						<th id = "quantity"><a href = "#">Quantity</a></th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody class = "pagination-container"></tbody>
			</table>
			
			<div class = "pagination-nav"></div>
		</div>
	</div>
{% endblock %}